# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6896fa6a4b66039b815f471c88ad8e465ba5b7f7ea715179ad4d14330f0eb4acea2f993e5d9410949ec3975ca831240c249b40b6d25e67fa5fe42d3a0d0ab8c5

test:
  secret_key_base: d60be087234aac99f390285f15840458dc2cdd84c7aaa80939479579fbb6f31f9918612d151efa7268c54c1d1213a8b14dfb148155f8c14e3437293034f69bfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
